#!/usr/bin/env python3
"""Rebuild cameras.js and images/ for traffclip from Louisiana 511 (LA DOTD).

Finds live cameras by probing LA DOTD's public HLS servers, names them from
tools/names.json (read off the on-video captions) or the state's open-data
camera list, and saves one frame per camera to images/<id>.jpg.

Needs Python 3 and ffmpeg (only for the frames). The page itself needs neither.

  python3 tools/refresh.py              scan, name, grab every frame
  python3 tools/refresh.py --new-only   same, but only grab frames that are missing
  python3 tools/refresh.py --no-frames  scan and name only
  python3 tools/refresh.py --frames-only
"""
import concurrent.futures as cf
import datetime
import json
import os
import re
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0 Safari/537.36")
OPEN_DATA = ("https://services1.arcgis.com/fXHQyq63u0UsTeSM/arcgis/rest/services/"
             "DOTD_Traffic_Cameras/FeatureServer/0/query?where=1%3D1&outFields=Name,VideoUrl&f=json")

# Camera ids are <prefix>-cam-NNN and numbering is sparse (lkc-cam-897 is I-210
# at Broad St, br-cam-8xx are I-110, ns-cam-528 is I-55), so every
# region gets the whole 001-999 range probed.
REGIONS = {
    "br":  ("Baton Rouge",  "ITSStreamingBR.dotd.la.gov"),
    "nor": ("New Orleans",  "ITSStreamingNO.dotd.la.gov"),
    "ns":  ("North Shore",  "ITSStreamingNO.dotd.la.gov"),
    "hou": ("Houma",        "ITSStreamingNO.dotd.la.gov"),
    "laf": ("Lafayette",    "ITSStreamingBR2.dotd.la.gov"),
    "lkc": ("Lake Charles", "ITSStreamingBR2.dotd.la.gov"),
    "shr": ("Shreveport",   "ITSStreamingBR2.dotd.la.gov"),
    "mnr": ("Monroe",       "ITSStreamingBR2.dotd.la.gov"),
    "alx": ("Alexandria",   "ITSStreamingBR2.dotd.la.gov"),
}


def get(url, timeout=15):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read()


def stream_url(prefix, n):
    return f"https://{REGIONS[prefix][1]}/public/{prefix}-cam-{n:03d}.streams/playlist.m3u8"


def is_live(url):
    try:
        return b"#EXTM3U" in get(url)[:200]
    except Exception:
        return False


def scan():
    found = []
    nums = range(1, 1000)
    with cf.ThreadPoolExecutor(16) as ex:
        for prefix in REGIONS:
            hits = [n for n, ok in zip(nums, ex.map(lambda n: is_live(stream_url(prefix, n)), nums)) if ok]
            print(f"  {prefix}: {len(hits)}", flush=True)
            found += [(prefix, n) for n in hits]
    return found


def open_data_names():
    try:
        feats = json.loads(get(OPEN_DATA, 30))["features"]
    except Exception as e:
        print("  open data unavailable:", e)
        return {}
    names = {}
    for f in feats:
        a = f["attributes"]
        m = re.search(r"/public/([a-z]+-cam-\d+)\.streams", a.get("VideoUrl") or "")
        if m and a.get("Name"):
            names[m[1]] = a["Name"].strip()
    return names


def load_cameras():
    with open(os.path.join(ROOT, "cameras.js")) as f:
        src = f.read()
    return json.loads(src[src.index("["):src.rindex("]") + 1])


def write_cameras(cams):
    lines = ",\n".join(json.dumps(c, ensure_ascii=False) for c in cams)
    stamp = datetime.date.today().isoformat()
    with open(os.path.join(ROOT, "cameras.js"), "w") as f:
        f.write(f"// Generated by tools/refresh.py on {stamp}. {len(cams)} cameras.\n")
        f.write(f"window.CAMERAS = [\n{lines}\n];\n")


def grab(cam):
    out = os.path.join(ROOT, "images", cam["id"] + ".jpg")
    tmp = out + ".part.jpg"
    cmd = ["ffmpeg", "-nostdin", "-v", "error", "-user_agent", UA, "-rw_timeout", "20000000",
           "-i", cam["url"], "-frames:v", "1",
           # apply the stream's pixel aspect so the still matches the live video's shape
           "-vf", "scale=trunc(iw*sar/2)*2:ih,setsar=1,scale='min(480,iw)':-2", "-q:v", "5", "-y", tmp]
    try:
        subprocess.run(cmd, timeout=60, capture_output=True)
    except subprocess.TimeoutExpired:
        pass
    if os.path.exists(tmp) and os.path.getsize(tmp) > 0:
        os.replace(tmp, out)
        return True
    if os.path.exists(tmp):
        os.remove(tmp)
    return False


def main():
    args = set(sys.argv[1:])
    if "--frames-only" in args:
        cams = load_cameras()
    else:
        print("scanning DOTD stream servers")
        found = scan()
        if not found:
            sys.exit("no cameras answered (offline?); cameras.js left unchanged")
        print("naming")
        manual_path = os.path.join(ROOT, "tools", "names.json")
        manual = {}
        if os.path.exists(manual_path):
            with open(manual_path) as f:
                manual = json.load(f)
        listed = open_data_names()
        cams = []
        for prefix, n in found:
            cid = f"{prefix}-cam-{n:03d}"
            region = REGIONS[prefix][0]
            name = manual.get(cid) or listed.get(cid) or f"{region} camera {n}"
            cams.append({"id": cid, "name": name, "region": region, "url": stream_url(prefix, n)})
        write_cameras(cams)
        print(f"wrote cameras.js ({len(cams)} cameras)")
    if "--no-frames" in args:
        return
    os.makedirs(os.path.join(ROOT, "images"), exist_ok=True)
    if "--new-only" in args:
        cams = [c for c in cams if not os.path.exists(os.path.join(ROOT, "images", c["id"] + ".jpg"))]
    print(f"grabbing {len(cams)} frames")
    ok = 0
    with cf.ThreadPoolExecutor(6) as ex:
        for cam, got in zip(cams, ex.map(grab, cams)):
            ok += got
            if not got:
                print("  no frame:", cam["id"], flush=True)
    print(f"frames: {ok}/{len(cams)}")


if __name__ == "__main__":
    main()
